### ISSUE TITLE
Unable to create VMs in a non-default AWS EC2 region 

### ISSUE THREAD

**Issue by pe-pan** [CloudSlang/cs-content#994]
I was playing with AWS EC2 and realized I can create new VMs in US East 1 region only (N. Virginia) but not in US East 2 region (Ohio).

After some googling, I found this: **by default you're actually asking us-east-1 to create the instance**

See here: https://stackoverflow.com/questions/22048081/invalid-availability-zone-when-creating-instance 

In other words, to be able to work with instances in non-default regions, one has to specify the availability_zone parameter.
In this doc, I found which endpoint can be used to access us-east-2: http://docs.aws.amazon.com/general/latest/gr/rande.html

Originally I was using **[deploy_instance.sl](https://github.com/CloudSlang/cs-content/blob/master/content/io/cloudslang/amazon/aws/ec2/deploy_instance.sl)** flow. 
Unfortunately, it seems the endpoint value (**https://ec2.amazonaws.com**) is built-in in the flow and cannot be changed (line #360).

**I believe it’s a bug.**

Anyway, I switched to **[run_instances.sl](https://github.com/CloudSlang/cs-content/blob/master/content/io/cloudslang/amazon/aws/ec2/instances/run_instances.sl)** flow where the endpoint parameter’s default value is set but can be overwritten.

When I set the endpoint value to **https://ec2.us-east-2.amazonaws.com**, I’m getting this error in the log.

_Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'SecretAmazonKey/ps://ec2/ec2/aws4_request,'_

**I believe it's another bug.**

Here is the flow I’m running:

```
namespace: content.io.cloudslang.demo
imports:
  ec2: io.cloudslang.amazon.aws.ec2

flow:
    name: deploy_AWS_VM

    inputs:
      - identity: 
      - credential: 
      - image_id: 'ami-c5062ba0'  # amazon linux image at us-east-2b
#      - image_id: 'ami-8c1be5f6'  # amazon linux image us-east-1c
      - instance_type: 't2.micro'

    workflow:
      - deploy_instance:
          do:
#            ec2.deploy_instance:
            ec2.instances.run_instances:
              - identity
              - credential
              - image_id
              - instance_type
              - endpoint: 'https://apigateway.us-east-2.amazonaws.com'
#              - availability_zone: 'us-east-1c'  # N.Virginia
              - availability_zone: 'us-east-2b'   # Ohio
          publish:
            - instance_id
            - ip_address
            - return_result
            - return_code
            - exception
          navigate:
            - SUCCESS: SUCCESS
            - FAILURE: FAILURE

    outputs:
        - instance_id
        - ip_address
        - return_result
        - return_code
        - exception

    results:
      - SUCCESS
      - FAILURE

```

**Comment by lrevnic** [comment]
@pe-pan have you tried this path for your second issue? 
https://stackoverflow.com/questions/24744205/ec2-api-error-validating-access-credential
